### ISSUE TITLE
Check for update on start-up / download new version option

### ISSUE THREAD

**Issue by irsdl** [nccgroup/BurpSuiteLoggerPlusPlus#16]
It will be good to create an option for check-for-update on start-up. This can be automatically enabled when it has not been installed directly from BApp store on first install.

Downloading the new version from Github seems like a good option and it should be optional for non-BApp store users only.

**Comment by CoreyD97** [comment]
In the next release the plugin will automatically check for a new release on an opt-out basis. If a newer release is found the user is prompted to install it whereby the plugin will download and replace the current jar file ready for the user to reload the plugin.
