### ISSUE TITLE
Feature Request - Dynamic Filtering

### ISSUE THREAD

**Issue by BSec** [nccgroup/BurpSuiteLoggerPlusPlus#17]
Hi Soroush Dalili,

Logger++ is a nice plugin to work with.
I was thinking that it would be good to have dynamic filtering within our plugin based on the regex value to search the response / requests for required items or information.

In the current version we have added regex to see the response page title. If we can have same functionality with help of a user input field to accept user's regex expression and display only those records dynamically which matches the regex criteria.

Usefulness:
1) Easy to capture error messages.

2) Easy to capture information leakage areas unlike predefined keywords search. (generally inside of an organization we know what we are testing so it would be good to check only those keywords which are required - https://github.com/fuzzdb-project/fuzzdb/tree/master/regex).

3) Easy to find SQL Injections.

4) Lot more possibilities.

Hope you like this idea !!

Thanks & Regards
Bhaskar  From 'BaanuTech'

**Comment by irsdl** [comment]
Thanks for the suggestion. Filtering is one of the important feature that is on the plan. However, RegEx filtering is new so whenever I added the filtering I will try to implement that too.
In addition, logging based on the RegEx can be a good idea to not even log requests which do not match the RegEx to save memory and time!

At the moment you can right click on the column header and change its RegEx to anything you want to capture the patterns. We currently have 5 RegExes for requests and 5 RegExes for response and they should be completely editable.

**Comment by CoreyD97** [comment]
In the upcoming release a number of new features have been added. This includes the filtering of log items using any of the parameters available in the table. Such a filter may be to display only those who have a specific parameter or set a certain cookie.

Along with filtering specific items it is also possible to set color rules to highlight important table entries such as setting the foreground color of post requests to a certain host to red.

Both of these features support the use of a regex value. e.g. _PATH == /\/api\/.*/_ to match only url's starting /api/

Thanks,
Corey
