### ISSUE TITLE
Different request/response view

### ISSUE THREAD

**Issue by irsdl** [nccgroup/BurpSuiteLoggerPlusPlus#19]
Similar to repeater view:
top/bottom split
left/right split
tabs

**Comment by henshin** [comment]
I was about to suggest this. It would be really useful and shouldn't be too hard to implement.

**Comment by ngregoire** [comment]
+1, that would be really useful!

**Comment by CoreyD97** [comment]
All 3 suggested views are implemented and will be available in the next release along with a pop out view to be able to display logger while working with other tabs.

Thanks,
Corey

**Comment by ngregoire** [comment]
v3.0 is awesome, many thanks!! Note: there's a small bug in the "View" option (cf issue #28 )
