### ISSUE TITLE
Feature Request - automated log file saving

### ISSUE THREAD

**Issue by jack-brear-ncc** [nccgroup/BurpSuiteLoggerPlusPlus#20]
Hey Soroush,

It'd be really cool if there was a feature to specify a number of minutes and a directory location and have the logger write to a file every n minutes. I often forget logger is running and then close burp and, now that Burp uses projects, and doesn't save the logger tab, I lose all the logs :(

Cheers,
Jack

**Comment by CoreyD97** [comment]
Hey Jack,

This feature has been implemented and will be available in the upcoming release. Any issues please let me know!

Thanks, 
Corey
