### ISSUE TITLE
Logger++ does not log proxy request modifications

### ISSUE THREAD

**Issue by jksecurity** [nccgroup/BurpSuiteLoggerPlusPlus#22]
Hello,

Just wanted to let you know that I faced an issue with Logger++ today where requests coming from the proxy tool were logged without the modifications my plugin made. Requests from Repeater and Intruder were logged after the modifications.

Flow, another (open source) logging plugin for Burp, actually logged the requests with the modifications, as expected.

I don't have time to jump into your code right now, perhaps I can dig a little deeper next week.

**Comment by irsdl** [comment]
Could you please make sure that Logger++ is running next to (just one level higher or lower) than the other logging tools you are using and let me know the result?
Basically, this tool doesn't do anything special; it just capture anything that comes via Burp extension APIs. So it is important to run it in the right order (after your plugin)

**Comment by jksecurity** [comment]
Hello,

I just tested that but strangely enough this does not seem to make a difference. I reloaded logger++ so it was the very last plugin loaded. I got the following results for the exact same request:

Logger++

![image](https://cloud.githubusercontent.com/assets/13599703/18790574/98ea9640-81af-11e6-97cf-a37ff9c9482a.png)

Flow

![image](https://cloud.githubusercontent.com/assets/13599703/18790634/d4adb0fe-81af-11e6-8f41-949d27b1a762.png)

As you can see, the difference is the custom header that I added using a plugin that hooks processHttpMessage.

**Comment by irsdl** [comment]
This is very strange. Could you please take the screenshot of the Burp Extensions order? I want to see where Flow vs Logger++
At the moment I am having a test myself with a new extension that changes a header in session handling - although the extension has been loaded after logger++, I can see the changes in it :(

**Comment by jksecurity** [comment]
Hello,

Just to be clear, I am not using ISessionHandlingAction but IHttpListener.

I am not sure what you mean by the burp extension order. Do you simply mean the order of the list under Burp Extensions? In that case, I've put Logger++ at the very end and Flow is right above it. My plugin is right above Flow:

My Plugin
Flow
Logger++

I doubt the order in this list matters though.

The only thing I can think of is that you can capture the request at two places: either when going out (messageIsRequest = true) or when a response is received. Perhaps there is a difference between those two request objects in Burp?

**Comment by jksecurity** [comment]
Hello,

I have just built a custom version of Logger++ and I can confirm that processProxyMessage is causing the issue! I just changed the code so that all tools are processed from processHttpMessage and then it logs modified requests just fine.

    //
	// implement IHttpListener
	//

	@Override
	public void processHttpMessage(int toolFlag, boolean messageIsRequest, IHttpRequestResponse messageInfo)
	{
		logIt(toolFlag, messageIsRequest, messageInfo, null);
	}

	//
	// implement IProxyListener
	// This is used next to IHttpListener to retrieve more data from the Proxy tab such as the listener port or  the client IP
	//
	
	/*
	@Override
	public void processProxyMessage(boolean messageIsRequest,
			IInterceptedProxyMessage message) {
		logIt(callbacks.TOOL_PROXY, messageIsRequest, null, message);

	}
	*/

Potentially the reason is that I also modify my requests by hooking this function. Another plausible explanation is that this is a bug in Burp. I will make a post on their forums to find out.

I attached an example plugin to prove my point.

[BurpExtender.java.txt](https://github.com/nccgroup/BurpSuiteLoggerPlusPlus/files/494044/BurpExtender.java.txt)

**Comment by jksecurity** [comment]
Also posted this as a bug report to Portswigger here: https://support.portswigger.net/customer/portal/questions/16696222-processproxymessage-doesn-t-take-changes-from-processhttpmessage-into-account

I am curious whether Portswigger considers this a bug or intended behavior.

**Comment by irsdl** [comment]
Thanks for finding the reason behind this issue. Maybe that listener was not created for this purpose but we have no replacement for it if we want to add more features in future (in fact I was using a generic listener in the initial versions). 
The reason why I used another listener for the proxy was to capture more data such as port number. I also have a plan to show open requests (without response) and this is only possible in proxy at the moment as requests and responses use a reference number. Otherwise, you have to create hash of a request or add a header to every request so you can match it when you have the response; however, hashing is not a good idea as it is memory intensive (make the whole app very slow) and repetitive requests will be confusing. Adding a header to every request can also cause issues for those app that reject requests with unknown or unwanted headers.

I shall probably use both of them when the tool is proxy. I will fix this in next update as well but can't give you an ETA.

**Comment by jksecurity** [comment]
It could still be a bug in Burp in which case you don't have to update anything. Let's see what they say about it.

**Comment by jksecurity** [comment]
https://support.portswigger.net/customer/en/portal/questions/16696804-processproxymessage-doesn-t-take-changes-from-processhttpmessage-into-account?new=16696804

Bummer, it seems that the order in which these hooks are processed is causing the problem. I will just use a custom version of Logger++ as I don't care that much for the proxy details...
