### ISSUE TITLE
Save Data

### ISSUE THREAD

**Issue by kgarmin** [nccgroup/BurpSuiteLoggerPlusPlus#24]
Hi,
For Logger++, you state:

**Note 2: In order to save the data automatically, use **Options>Misc>Logging.**** 

Under which Burp tab is the Logging option? User Options? Project Options? Proxy?  I think you are referring to Project Options, but I'm not sure.

I need to save the data as it is generated, since Burp has a habit of crashing.  Will automatic logging save data to the .csv file as it is generated?  Thank you.

**Comment by CoreyD97** [comment]
The latest releases contain additional functionality to automatically log all entries to a CSV file in the Logger++ options tab.

Thanks,
Corey
