### ISSUE TITLE
Incorrect processing of display options

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/BurpSuiteLoggerPlusPlus#28]
![loggerpp](https://user-images.githubusercontent.com/4039324/29568227-feca054e-874f-11e7-8f12-82576c67fb70.png)
When modifying option "View" from the menu bar, it is possible to have more than one option checked ("Top/Bottom" and "Tabs" in the attached screenshot). And the GUI was using "Tabs". The other option "Request/response view" seems OK.

Testbed: Linux + Burp Suite Pro v1.7.26 + Sun Java 1.8.0_144-b01

**Comment by CoreyD97** [comment]
Thank you, I'll take a look at that now. I cannot see the attached screenshot though, am I right in saying the GUI displays fine but the view options show a different / multiple views are in use?

Thanks,
Corey

**Comment by ngregoire** [comment]
Yes, you're right. If needed, you can dowload a copy from http://wikisend.com/download/112818/loggerpp.png

**Comment by CoreyD97** [comment]
Thank you, this has been fixed. A release for this issue and a few others will be released very shortly.
