### ISSUE TITLE
No documentation about filters

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/BurpSuiteLoggerPlusPlus#29]
Having a list of all properties + a few examples would be awesome.

**Comment by CoreyD97** [comment]
Sorry that this is not currently available. Due to invalid permissions on the repository I could not create a wiki upon release. I will correct some information that has changed since I first wrote the page and post it here on GitHub.

Thanks,
Corey

**Comment by CoreyD97** [comment]
A basic wiki page should be available now. If there's anything you'd like me to clarify I'm happy to do so. 

Thanks,
Corey
