### ISSUE TITLE
Table view improvements

### ISSUE THREAD

**Issue by inquisb** [nccgroup/BurpSuiteLoggerPlusPlus#3]
The Logger++ is a great extension, but I find it slightly unusable at this stage: it has way too many unnecessary columns. In my opinion a number of columns should be optional (to be configured from Options tab):
* Host should have exact same format as Host in Proxy tab (http://...).
* URL should have exact same format as URL in Proxy tab (/relative_path only).
* Method should be after Host.
* Port should be after URL and optional.
* Req Type same format as in MIME type in Proxy tab and optional.
* Remove the dot (.) from the Extension field.
* Referrer URL renamed to Referred and optional.
* QS? – is it Query String? If so, group it under Params like in Proxy tab.
* BodyParam? Group it under Params like in Proxy tab.
* Cookie? renamed to Sent Cookies and I do actually care to see them, like in Proxy tab.
* Req Length optional.
* Resp Type same format as in Proxy tab.
* Merge Detected Type and Inferred Type and optional.
* Set-Cookies? renamed to Set-Cookie and I do actually care to see them, like in Proxy tab.
* Resp Length optional.
* Does the Comment field auto-update if I update it in Proxy/Target?

**Comment by irsdl** [comment]
I am trying to make the fields dynamic so then users can enable/disable, rename, or re-order them.

"Does the Comment field auto-update if I update it in Proxy/Target?"
> I cannot do this as extensions do not have any power to find the same requests in the sitemap (there is no unique reference to requests/responses). Burp suite also does not share the comments in between Proxy and Target as far as I know.
