### ISSUE TITLE
Extension requires reloading to display other extensions on occasion.

### ISSUE THREAD

**Issue by CoreyD97** [nccgroup/BurpSuiteLoggerPlusPlus#30]
Sometimes, when logger++ is not the last extension to be loaded, it causes any extensions after itself to not load. This can be fixed by reloading the extension.

**Comment by gavz** [comment]
example plugin https://github.com/bugcrowd/HUNT when load hunt_methodology.py

**Comment by CoreyD97** [comment]
No longer seems to be the case. Closing the issue.
