### ISSUE TITLE
.csv file won't show POST payloads.

### ISSUE THREAD

**Issue by kawaxi** [nccgroup/BurpSuiteLoggerPlusPlus#36]
When exporting the requests into a file, POST requests won''t show the postdata or payloads used in these, they correctly register in the Logger++ proxy UI tho.

Please let me know if you need more info.

**Comment by CoreyD97** [comment]
Thanks to @kawaxi this issue was tracked down to be caused by the logger only automatically logging updated entries, instead of new entries. The issue was fixed as of 12/12/2017 along with a few other issues found on during our debugging process! Commit Ref: 95da6a2
