### ISSUE TITLE
Additional "Clear logs" button in the main view

### ISSUE THREAD

**Issue by ngregoire** [nccgroup/BurpSuiteLoggerPlusPlus#37]
I use the "Clear the logs" button (located in the "Options" tab) quite often, so I'm constantly switching between "View logs" and "Options".

It would be nice to have another "Clear logs" button in the "View logs" tab, next  to the "Colorize" one.

Btw, thanks for this very useful extension!

**Comment by CoreyD97** [comment]
Just added this for you!

Glad you find it useful, if there's anything else you need let me know!

**Comment by ngregoire** [comment]
Perfect, many thanks!
