### ISSUE TITLE
Distinguish requests generated by a session handling rule

### ISSUE THREAD

**Issue by inquisb** [nccgroup/BurpSuiteLoggerPlusPlus#4]
If possible, add a column to distinguish between requests generated automatically by a session handling rule (e.g. a macro) and performed manually (via Intruder, Repeater, Scanner, etc.).
At the moment if I have a session handling rule that runs a macro that does 10 requests and I send to the Scanner a request associated to such a rule, I have no easy way to distinguish between the ones generated by the session handling rule and the ones generated by the Scanner.

**Comment by irsdl** [comment]
Burp does not give extensions this ability to verify whether a request has already been manipulated by any of the tools (to for example say this request has been changed by session handling rule or which rule in session handling rule or another extension). Therefore, it is impossible to implement this at the moment. This will also add an overhead to burp suite if it wants to be implemented. You can always use the Sessions Tracer in burp to monitor this but it will make it slow.
The workaround is to use the Tool column to detect this.

**Comment by irsdl** [comment]
A new column has been added that shows if a request uses any sessions from the "Cookie jar". This may make the situation better.
