### ISSUE TITLE
Need to know logger++ column definitions in detail

### ISSUE THREAD

**Issue by ritesh12** [nccgroup/BurpSuiteLoggerPlusPlus#40]
Hi,

I am currently using Burp Tool & using extension called logger++. Can anybody guide me on the columns definitions that it will useful for me provided in logger++ table? Each column might have some definition. I am attaching the screenshot as well 

![logger table](https://user-images.githubusercontent.com/20737439/39571920-c918ffe6-4eea-11e8-9e95-f7abd4564ce1.PNG)

**Comment by CoreyD97** [comment]
https://github.com/nccgroup/BurpSuiteLoggerPlusPlus/wiki/Filter-Fields

Hopefully this will be of help to you.
