### ISSUE TITLE
Elasticsearch could not be enabled

### ISSUE THREAD

**Issue by ryanvillarreal** [nccgroup/BurpSuiteLoggerPlusPlus#41]
I'm getting an error message for the Elastic search enable feature.  It says None of the configured nodes are available.  

I didn't see any other open or closed issues regarding this feature so I thought I would reach out.  

I have Elkstack running and can pipe files or syslogs into 127.0.0.1:9300 but the connection cannot be made from Logger++. 

Thanks,
Ryan

**Comment by ryanvillarreal** [comment]
Finally figured it out.  My fault.

**Comment by tkal** [comment]
@ryanvillarreal how did you manage to solve this? I'm having the same issue.

**Comment by ryanvillarreal** [comment]
> @ryanvillarreal how did you manage to solve this? I'm having the same issue.
@tkal I think it has to do with the Cluster Name.  You need to make sure it matches your cluster name.  the default from Logger++ is elasticsearch.  I was running mine in a docker environment so it was docker-cluster.
