### ISSUE TITLE
Export created filters (regular||colors)

### ISSUE THREAD

**Issue by ours-code** [nccgroup/BurpSuiteLoggerPlusPlus#43]
Hello,

Thank you for that usefull extension. 
We wish there was an export functionality to share our filters across the team. Is there a way to do that or an implementation of this planned in a future release ?

Thank you,

**Comment by CoreyD97** [comment]
Hey! 
Glad you're finding the extension helpful, this isn't something I'd considered before but I'll have a go at implementing this and your other request today. 

If you've got any other ideas I'd be happy to hear them!

Thanks,
Corey
