### ISSUE TITLE
Have an "Apply" button when editing color filters

### ISSUE THREAD

**Issue by ours-code** [nccgroup/BurpSuiteLoggerPlusPlus#44]
Hello,

It would be nice to have an apply button when you edit color filters. Otherwise you have to close the editing windows to see if filter works and reopen & resize it (especially when working with long regexes).

Thank you,

**Comment by CoreyD97** [comment]
Looks like I previously had the code ready to do this automatically but forgot to fire the events when a change was made. I'm going to implement a few of your other changes and then push a new build for you!

Thanks,
Corey

**Comment by ours-code** [comment]
Great, nice to hear. I have an other enhancement idea I create soon, would be great if you can include it in your upcoming release :)
