### ISSUE TITLE
Have the view logs window in floating mode

### ISSUE THREAD

**Issue by ours-code** [nccgroup/BurpSuiteLoggerPlusPlus#47]
Hi,

Would it be possible to have a floating "view logs" window ?

Thank you,

**Comment by CoreyD97** [comment]
Hello,

Is this only the view logs window you wish to have floating? Or all of the Logger++ tab? 
Currently the whole Logger++ tab can be floated by the button on the navbar, next to help.

If you wish to be able to detatch the view logs tab entirely I can add the ability to do this separately from the rest of the windows.

Thanks,
Corey

**Comment by ours-code** [comment]
Having the whole Logger++ tab floating is perfectly fine, I just miss that functionality.
Thanks !
