### ISSUE TITLE
Storage accross a Burp session

### ISSUE THREAD

**Issue by righettod** [nccgroup/BurpSuiteLoggerPlusPlus#53]
Hello,

It is planned to add the possbility to save and autoload the requests/responses sent by other components than the Proxy accross the reload of a Burp session file ?

The final objective will be to have the capacity to generate a full work log of all the requests send via Burp on a entire mission performed with Burp on severals days (session stop and reload).

Thanks in advance for your feedback :smiley:

**Comment by CoreyD97** [comment]
Hey!

At the moment, the Burp Suite API does not provide a method of storing and retrieving the responses beyond what is stored from the proxy. Currently we just import what is stored in Burp itself into our format. It would be possible to do so separately from the session but would quickly get messy.

Hopefully the upcoming major release version will have functionality which may allow this to be integrated though for now I can only recommend having Logger++ output the table as a CSV each day and combining at the end. 

Sorry for the inconvenience!

**Comment by righettod** [comment]
Hi,

Thanks you very much for the your feedback.

On the side, i have developed this little extension the create an audit trail of an assessment session:

https://github.com/righettod/activity-trail-log

Thanks again for the feedback and for your amazing extension :smiley:
