### ISSUE TITLE
Sorting Response Delay column gives unexpected results

### ISSUE THREAD

**Issue by dfc** [nccgroup/BurpSuiteLoggerPlusPlus#54]
When I sort the "Response Delay" column in increasing order (▲) I get unexpected results: 

```
189ms
18ms
191ms
199ms
1ms
1ms
1s0ms
1s17ms
1s183ms
1s19ms
1s214ms   
1s21ms
1s441ms
1s51ms
1s84ms
1s890ms
200ms
290ms
20ms
```

The obvious problem is that "1 second 890 ms" should come after "20ms". 

What is especially weird is that it sorts 1.214 before 1.021 yet lists 1.084 before 1.890:

```
1s214ms   
1s21ms
...             
1s84ms
1s890ms
```

Burp Version             1.7.36 
Java Version             1.8.0_112-b15

**Comment by ngregoire** [comment]
Storing delays as integers would be useful. Sorting and filtering are a PITA when dealing when strings looking like numbers. And I can confirm the bug regarding the values themselves (https://github.com/nccgroup/BurpSuiteLoggerPlusPlus/issues/38)...

**Comment by CoreyD97** [comment]
An incoming update replaces the useless current string based display with a numerical value measured in milliseconds.
