### ISSUE TITLE
Feature request - Macros in Tools

### ISSUE THREAD

**Issue by Hipapheralkus** [nccgroup/BurpSuiteLoggerPlusPlus#69]
I'm not certain it's possible to achieve, but in the View Logs, I can see Tool {Scanner, Repeater, Extender, ...}. Would it be possible to also differentiate those, coming from Macros (initiated by Scanner for instance)? For example, the "Macro" or "Post request macro", to highlight which request is used by Macros. If I'm testing more complex setup, with a few pre-request macros (e.g. session management, and getting fresh CSRF tokens), and testing some request in Active scanner, and running a few post-request macros to finish the multi-step operation and get results, it would help me to see which requests are made by Macros.

**Comment by CoreyD97** [comment]
Apologies, but due to limitations with the Burp API, it is not possible to get this information with the current state of the API.

If this changes, I'll definitely add this feature!
