### ISSUE TITLE
[Feature] Predefined colorize palette combinations.

### ISSUE THREAD

**Issue by Shaddy** [nccgroup/BurpSuiteLoggerPlusPlus#77]
# Predefined colors for Colorize

## Problem

Currently, we have many options that allow complete control about which color will be used as a **background**, or **foreground**.

![image](https://user-images.githubusercontent.com/247221/63030205-3c802d00-beb2-11e9-8bfa-39841521aa10.png)

Also, we have the preview of the row if we select that color.

![image](https://user-images.githubusercontent.com/247221/63029455-e2cb3300-beb0-11e9-9ebe-d0361da28872.png)

One of the problems is that it doesn't use the actual background or foreground (text) color so we can't predict how the real color will be.

If we want highlights like the following, we can't have the final preview.

![image](https://user-images.githubusercontent.com/247221/63029602-21f98400-beb1-11e9-8019-b80e8f4a1d53.png)

While we have the `Recent` window, that allows us to predefine a set of colors to **Foreground** or **Background**

![image](https://user-images.githubusercontent.com/247221/63029859-92a0a080-beb1-11e9-83f7-0af62984ecf3.png)

It turns to colorize a filter into a bunch of clicks, for each filter, and if you're used to having "temporal" burp instances, it can be tedious to configure it every time.

What about a predefined set of **Foreground** and **Background** combinations customizable by the user?

## Proposed Solution

Instead of having **Foreground** or **Background** as the first option for a filter.

![image](https://user-images.githubusercontent.com/247221/63030452-a39de180-beb2-11e9-8c05-44309cb5eb5b.png)

Is it possible to have a drop-down predefined configuration? Something similar to what repeater does in the contextual menu for *Proxy*.

![image](https://user-images.githubusercontent.com/247221/63030656-f8415c80-beb2-11e9-8b88-58a29ff2cc87.png)

Having it both in colorize menu and configurable as a contextual menu option will be amazing.

## Final

I am aware that this can be not a priority or too complex to be worthy, anyway, I would love to hear what you think.

Thanks!

**Comment by CoreyD97** [comment]
Hey!
Thanks for the idea, I do think that predefined color combinations would be useful and I do understand that it can be time-consuming to find combinations that work nicely.

I've just rewritten the logic for modifying color filters, so changes made in the color filter dialog are visible instantly, without the need to close the dialog to see the changes. Hopefully this will make the process slightly less painful in the meantime. I'll be pushing a pre-release build with this change in soon.

Thanks,
Corey

**Comment by Shaddy** [comment]
@CoreyD97 I've tested this and I think for now is really useful. Thanks for that!

**Comment by CoreyD97** [comment]
Glad to hear it! 👍
