### ISSUE TITLE
Error when "Remove Item"

### ISSUE THREAD

**Issue by theblackturtle** [nccgroup/BurpSuiteLoggerPlusPlus#85]
Hi, When you select multiple items and click "Remove Item", it will raise an error. I checked debug log but not show anything.

**Comment by CoreyD97** [comment]
Thanks for the heads up, I'll take a look at this one. Is this on 
 v3.13-beta ebf1d041ab782cb30e638113072b4030a503b05c?

**Comment by theblackturtle** [comment]
Yes, I use v3.13-beta version.

**Comment by CoreyD97** [comment]
Could you please share the error that you're seeing? I can remove multiple items without any issues.
